# name: Sync to gitlab CI
# on:
#   push:
#     branches:
#       - development
#       - staging
#       - main

# jobs:
#   sync:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repository code
#         uses: actions/checkout@v4
#       - uses: keninkujovic/gitlab-sync@2.0.0
#         with:
#           gitlab_url: ${{ secrets.GITLAB_URL }}
#           username: ${{ secrets.GITLAB_USERNAME }}
#           gitlab_pat: ${{ secrets.GITLAB_PAT }}

name: Sync to gitlab CI
on:
  push:
    branches:
      - development
      - staging
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: keninkujovic/gitlab-sync@2.0.0
        with:
          gitlab_url: https://gitlab.com/rifqiahmadf/praktik-cicd-github.git
          username: rifqiahmadf
          gitlab_pat: ${{ secrets.GITLAB_PAT }}